# Site settings
author: taryn yaeger
title: Problem/Solution
header-img: img/home-bg.png
email: tsyaeger@gmail.com
copyright_name: taryn yaeger
description: > # this means to ignore newlines until "baseurl:"
  "Architecture begins when you place two bricks carefully together."
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tsyaeger

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
